name: Test

on:
  push:
    branches:
      - main

env:
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: 5.14.0
  ARTIFACT: qt-planets-linux-build.AppImage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
            
          
      - name: Install Qt
        if: steps.cache.outputs.cache-hit != 'true'
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          host: linux
          target: desktop
          arch: gcc_64
          dir: ${{ runner.temp }}/qt-5.14.0/
          modules: qtcharts qt3d
          setup-python: true


      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'

      - name: Verify CMake version
        run: cmake --version
     
      - name: print output
        run: |
          pwd
          ls BadgeProject/

      - name: Create build directory
        run: |
          mkdir BadgeProject/build
      

      - name: Configure CMake and build
        run: |
               export test_command=BadgeProject/test.sh
               source $test_command
               
#       - name: Configure CMake and build
#         run: |
#           cd BadgeProject/build
#           cmake ..
#           make
#           cd TestP
#           ctest -j4 --output-on-failure --extra-verbose --timeout 300 --coverage

  
