name: Build
on:
  push:
    branches:
      - main
env:
 SOURCE_DIR:   ${{ github.workspace }}
 QT_VERSION:   5.14.0
 ARTIFACT:     qt-planets-linux-build.AppImage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version:      ${{ env.QT_VERSION }}
          host:         linux
          target:       desktop
          arch:         gcc_64
          dir:          ${{ runner.temp }}
          modules:      qtcharts qt3d
          setup-python: true
              
      - name: Create build directory
        run:  mkdir ${{ env.SOURCE_DIR }}/build
        
        

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
         cmake-version: '3.16.x'
      - name: Use cmake
        run: cmake --version
        
      - name: Create build directory
        run:  mkdir ${{ env.SOURCE_DIR }}/build

      - name: Build
        run: cmake --build .

#       - name: Upload artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: my-app
#           path: |
#             bin/my-app
#             lib/libmylib.so
