name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Qt
        uses: qmc/install@v0
        with:
          qt-version: '5.15.2'
          components: qtbase qtdeclarative qttools

      - name: Setup CMake
        uses: actions/setup-cmake@v2
        with:
          cmake-version: '3.20.2'

      - name: Build
        run: cmake --build .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: |
            bin/my-app
            lib/libmylib.so
