name: Qt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Qt
        uses: qt/qt5/actions/setup@v1

      - name: Configure and build
        run: |
          mkdir build
          cd build
          qmake ..
          make

      - name: Run tests
        run: |
          cd build
          make check
