name: Build
on:
  push:
    branches:
      - main
env:
 SOURCE_DIR:   ${{ github.workspace }}
 QT_VERSION:   5.14.0
 ARTIFACT:     qt-planets-linux-build.AppImage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version:      ${{ env.QT_VERSION }}
          host:         linux
          target:       desktop
          arch:         gcc_64
          dir:          ${{ runner.temp }}
          modules:      qtcharts qt3d
          setup-python: false
              
      - name: Create build directory
        run:  mkdir ${{ env.SOURCE_DIR }}/build

#       - name: Setup CMake
#         uses: actions/setup-cmake@v2
#         with:
#           cmake-version: '3.20.2'

#       - name: Build
#         run: cmake --build .

#       - name: Upload artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: my-app
#           path: |
#             bin/my-app
#             lib/libmylib.so
